[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry_core>=1.0.0"]

[tool.poetry]
authors = ["Julianne Swinoga <julianneswinoga@gmail.com>"]
description = "Interface for FlightGear network connections"
license = "MIT"
name = "flightgear_python"
readme = "README.md"
version = "1.3.0"

[tool.poetry.dependencies]
construct = "^2.10"
# Following are pegged at the latest version that supports Python 3.6
multiprocess = "==0.70.12.2"
python = "^3.6"
requests = "2.27.1"

[tool.poetry.dev-dependencies]
GitPython = "==3.1.20"
JSBSim = "==1.1.11"
# Following are pegged at the latest version that supports Python 3.6
pytest = "==7.0.1"
pytest-cov = "^3.0.0"
pytest-mock = "==3.6.1"
sh = "^1.14.3"
sphinx = "^5.1.1"
sphinx-rtd-theme = "^0.5.2"  # Can't `poetry update` with 1.0.0?
sphinx_mdinclude = "^0.5.2"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/julianneswinoga/flightgear-python/issues"
"Documentation" = "https://flightgear-python.readthedocs.io/en/latest"
"Repository" = "https://github.com/julianneswinoga/flightgear-python"
